### ISSUE TITLE
Notes disappeared

### ISSUE THREAD

**Issue by gnumoksha** [aykit/MyOwnNotes#127]
The notes written in app before synchronization disappeared after receiving an invalid json

This is disturbing

**Comment by maltefiala** [comment]
Yes, this is not good indeed. We are still working on Version 2.0 and (still) hope to have it finished soon(tm). As it will be a complete rewrite, this issue won't occur any more in the future.

Regarding the error: Most of the json errors are because of the wrong app installed server side. The app you need is: https://github.com/owncloud/notes

**Comment by gnumoksha** [comment]
Yes, it was the wrong app

**Comment by maltefiala** [comment]
Ok. Unfortunately someone funny decided to name his server side app like ours which brings a lot of confusion to many people... Glad I could help.
