### ISSUE TITLE
MyOwnNotes 2.0 crashes in a systematic way

### ISSUE THREAD

**Issue by repsorp** [aykit/MyOwnNotes#143]
Systematic crash when trying to open a note, any note...
Everything used to be ok with v. 1.6

SYSTEM INFORMATION
Android version: 4.4.2 (cm_hammerhead-userdebug 4.4.2 KOT49H InstallerXNPQ08Q release-keys)
Device: LGE Nexus 5 (hammerhead)

03-28 08:01:27.933 I/ActivityManager(820): Timeline: Activity_windows_visible id: ActivityRecord{42c37e98 u0 org.aykit.MyOwnNotes/.activities.NoteListActivity t38} time:1636286
03-28 08:01:38.053 I/ActivityManager(12321): Timeline: Activity_launch_request id:org.aykit.MyOwnNotes time:1646406
03-28 08:01:38.053 I/ActivityManager(820): START u0 {cmp=org.aykit.MyOwnNotes/.activities.NoteDetailActivity (has extras)} from pid 12321
03-28 08:01:38.093 E/AndroidRuntime(12321): Process: org.aykit.MyOwnNotes, PID: 12321
03-28 08:01:38.093 E/AndroidRuntime(12321): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.aykit.MyOwnNotes/org.aykit.MyOwnNotes.activities.NoteDetailActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
03-28 08:01:38.093 E/AndroidRuntime(12321): 	at org.aykit.MyOwnNotes.activities.NoteDetailActivity.onCreate(NoteDetailActivity.java:26)
03-28 08:01:38.093 W/ActivityManager(820):   Force finishing activity org.aykit.MyOwnNotes/.activities.NoteDetailActivity
03-28 08:01:38.093 W/ActivityManager(820):   Force finishing activity org.aykit.MyOwnNotes/.activities.NoteListActivity
03-28 08:01:38.593 W/ActivityManager(820): Activity pause timeout for ActivityRecord{42acb5c8 u0 org.aykit.MyOwnNotes/.activities.NoteDetailActivity t38 f}
03-28 08:01:39.943 I/ActivityManager(820): Process org.aykit.MyOwnNotes (pid 12321) has died.
03-28 08:01:39.943 I/WindowState(820): WIN DEATH: Window{42bd4e50 u0 org.aykit.MyOwnNotes/org.aykit.MyOwnNotes.activities.NoteListActivity}

**Comment by repsorp** [comment]
Sorry... My bad
  •  Mobile device using Android Version >= 5.0
Didn't see that anywhere on f-droid

**Comment by repsorp** [comment]
Back to 1.6 so...

**Comment by repsorp** [comment]
4.1 or later...
![4 1](https://cloud.githubusercontent.com/assets/6297032/24467205/e1093be2-14b3-11e7-8753-dc96ad581d51.jpg)

**Comment by kernins** [comment]
Similar crash on 4.4.4

`java.lang.RuntimeException: Unable to start activity ComponentInfo{org.aykit.MyOwnNotes/org.aykit.MyOwnNotes.activities.NoteDetailActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime( 5221):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2215)
E/AndroidRuntime( 5221):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264)
E/AndroidRuntime( 5221):        at android.app.ActivityThread.access$800(ActivityThread.java:136)
E/AndroidRuntime( 5221):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1219)
E/AndroidRuntime( 5221):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5221):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 5221):        at android.app.ActivityThread.main(ActivityThread.java:5032)
E/AndroidRuntime( 5221):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5221):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 5221):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 5221):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 5221):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 5221): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime( 5221):        at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:310)
E/AndroidRuntime( 5221):        at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:279)
E/AndroidRuntime( 5221):        at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:253)
E/AndroidRuntime( 5221):        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
E/AndroidRuntime( 5221):        at org.aykit.MyOwnNotes.activities.NoteDetailActivity.onCreate(NoteDetailActivity.java:26)
E/AndroidRuntime( 5221):        at android.app.Activity.performCreate(Activity.java:5310)
E/AndroidRuntime( 5221):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
E/AndroidRuntime( 5221):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2179)
E/AndroidRuntime( 5221):        ... 11 more
W/ActivityManager( 1987):   Force finishing activity org.aykit.MyOwnNotes/.activities.NoteDetailActivity`
